### ISSUE TITLE
`cargo-1.58.0` - build problems

### ISSUE THREAD

**Issue by a-kenji** [oxalica/rust-overlay#84] opened 2022-04-16 08:10 UTC
Hi! Thank you for this amazing overlay.

I am having trouble lately with building the `1.58.0` toolchain with it.

This is the error, that I am getting:

```
nix log /nix/store/gjlydwwdlfqmd59ksng7ha2k7h7bh2lv-cargo-1.58.0-x86_64-unknown-linux-gnu.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/b4dg6532dfg1grk3949z6xgcvl6fcxz6-cargo-1.58.0-x86_64-unknown-linux-gnu.tar.xz
source root is cargo-1.58.0-x86_64-unknown-linux-gnu
setting SOURCE_DATE_EPOCH to timestamp 1641905058 of file cargo-1.58.0-x86_64-unknown-linux-gnu/version
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Installing component cargo
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu
shrinking /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu/bin/cargo
shrinking /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
gzipping man pages under /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu/share/man/
patching script interpreter paths in /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu
checking for references to /build/ in /nix/store/9mpy78rkzx5h7q5q7mwj3hp3gzxnvjcb-cargo-1.58.0-x86_64-unknown-linux-gnu...
automatically fixing dependencies for ELF files
/nix/store/sds4msgr38nfs2zg3fsrd54wv8sndlyx-auto-patchelf-hook/nix-support/setup-hook: line 220: -l: command not found
```

Maybe it is also an issue with my setup?

It has been happening now in two different environments for me:

Here is an example: https://github.com/a-kenji/zellij-nix/runs/6046299076?check_suite_focus=true#step:5:424

**Comment by oxalica** [comment] 2022-04-17 17:24
Duplicate of #83

**Closed by oxalica** 2022-04-17 17:24 UTC
Labels: bug

**Comment by a-kenji** [comment] 2022-04-17 19:26
Oh, my bad! I didn't realize they were the same issue, thanks!
